### ISSUE TITLE
大神，USART_CONTROL和COMMUNACATE c文件注释乱码了，可以加个联系方式请教一下吗

### ISSUE THREAD

**Issue by RictomW** [W3042578/FOC_Mini_Board#1]
大神，USART_CONTROL和COMMUNACATE c文件注释乱码了，可以加个联系方式请教一下吗

**Comment by W3042578** [comment]
你好，原先的代码架构混乱，现在已经重新调整架构并添加注释，USART_CONTROL的内容不会用到，注释乱码可能是字符转换问题，后续我再全部更改为utf-8

**Comment by W3042578** [comment]
可以加qq 2982055579 联系，之前半年都在忙工作，抱歉
